window.Vue = require("vue");
const app = new Vue({
  el: "#app",
  data: {
    arts: [
      {
        title: "Responsive Responsive DigitalOcean Sammy the Shark",
        image: "/img/sammy-the-shark.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/gOMJPxy",
        github: "https://github.com/purecss-co/sammy-the-shark",
        website: "https://www.digitalocean.com/",
        design: "",
        border: "",
      },
      {
        title: "Responsive JomLaunch Logo",
        image: "/img/jomlaunch.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/rNLbvZp",
        github: "https://github.com/purecss-co/jomlaunch-logo",
        website: "https://launch.jomweb.my/",
        design: "",
        border: "",
      },
      {
        title: "Responsive Sports Car",
        image: "/img/sports-car.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/ZEQXXrx",
        github: "https://github.com/purecss-co/sports-car",
        website: "",
        design: "https://dribbble.com/shots/3252634-Sports-Car",
        border: "",
      },
      {
        title: "Responsive Chris Coyier Pixel Avatar",
        image: "/img/chris-coyier.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/RwraJRm",
        github: "https://github.com/purecss-co/chris-coyier-pixel-avatar",
        website: "",
        design: "",
        border: "",
      },
      {
        title: "Responsive Tesla Logo",
        image: "/img/tesla.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/MWKaQBZ",
        github: "https://github.com/purecss-co/tesla-logo",
        website: "https://www.tesla.com",
        design: "",
        border: "border-top",
      },
      {
        title: "Responsive SpaceX Logo",
        image: "/img/spacex.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/yLeYPyr",
        github: "https://github.com/purecss-co/spacex-logo",
        website: "https://www.spacex.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive My Pixel Avatar",
        image: "/img/pixel-avatar.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/qBbBXxB",
        github: "https://github.com/purecss-co/my-pixel-avatar",
        website: "",
        design: "",
        border: "",
      },
      {
        title: "Responsive 3D Ball",
        image: "/img/3d-ball.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/dyYeBgv",
        github: "https://github.com/purecss-co/3d-ball",
        website: "",
        design: "",
        border: "",
      },
      {
        title: "Responsive Bear",
        image: "/img/bear.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/rNOdRXM",
        github: "https://github.com/purecss-co/bear",
        website: "",
        design: "https://dribbble.com/shots/11321693-Bear",
        border: "",
      },
      {
        title: "Responsive Hijab Girl Portrait",
        image: "/img/hijab-girl.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/bGVYOjY",
        github: "https://github.com/purecss-co/hijab-girl",
        website: "",
        design: "https://dribbble.com/shots/5950905-Veil-Logo",
        border: "border-top",
      },
      {
        title: "Responsive Lady in Blue Portrait",
        image: "/img/lady-in-blue.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/zYvwemL",
        github: "https://github.com/purecss-co/lady-in-blue",
        website: "",
        design: "https://dribbble.com/shots/11135126-Lady-In-Blue/",
        border: "border-top",
      },
      {
        title: "Responsive Mo Salah Poster",
        image: "/img/mosalah.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/QWjLqqx",
        github: "https://github.com/purecss-co/mo-salah-poster",
        website: "",
        design: "https://www.uplabs.com/posts/mohamed-salah-poster",
        border: "",
      },
      {
        title: "Responsive Dwayne Johnson (The Rock) Portrait",
        image: "/img/the-rock.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/WqQPRm",
        github: "https://github.com/purecss-co/purecss-dwayne-johnson",
        website: "",
        design: "",
        border: "",
      },
      {
        title: "Responsive Keanu Reeves (John Wick) Portrait",
        image: "/img/john-wick.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/qzBLVj",
        github: "https://github.com/purecss-co/purecss-keanu-reeves",
        website: "",
        design: "",
        border: "",
      },
      {
        title: "Responsive Gatsby Logo",
        image: "/img/gatsby.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/KLOwdz",
        github: "https://github.com/purecss-co/purecss-gatsby-logo",
        website: "https://www.gatsbyjs.org",
        design: "",
        border: "",
      },
      {
        title: "Responsive Sandwich",
        image: "/img/sandwich.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/byPLQK",
        github: "https://github.com/purecss-co/purecss-sandwich",
        website: "",
        design: "https://dribbble.com/shots/5312830-Sandwich",
        border: "",
      },
      {
        title: "Responsive Letter M",
        image: "/img/letter-m.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/OYqjRm",
        github: "https://github.com/purecss-co/purecss-letter-m",
        website: "",
        design: "https://dribbble.com/shots/6315007-M-Logo",
        border: "",
      },
      {
        title: "Responsive Letter T",
        image: "/img/letter-t.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/yWGwGx",
        github: "https://github.com/purecss-co/purecss-letter-t",
        website: "",
        design: "https://dribbble.com/shots/6176376-T-Letter-Logo",
        border: "",
      },
      {
        title: "Responsive Space Helemt",
        image: "/img/space-helmet.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/EzGmGR",
        github: "https://github.com/purecss-co/purecss-space-helmet",
        website: "",
        design: "https://www.uplabs.com/posts/astrounut-space-helmet",
        border: "",
      },
      {
        title: "Responsive Netlify Logo",
        image: "/img/netlify.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/PvyORQ",
        github: "https://github.com/purecss-co/purecss-netlify-logo",
        website: "https://www.netlify.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive Unicorn Logo",
        image: "/img/unicorn-logo.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/MdBeYg",
        github: "https://github.com/purecss-co/purecss-unicorn-logo",
        website: "",
        design: "https://dribbble.com/shots/5774723-Unicorn-logo",
        border: "",
      },
      {
        title: "Responsive Chrome V8 Logo",
        image: "/img/v8.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/KLRZqQ",
        github: "https://github.com/purecss-co/purecss-chrome-v8-logo",
        website: "https://v8.dev",
        design: "",
        border: "",
      },
      {
        title: "Responsive Bob The Minion",
        image: "/img/minion.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/wXjpyB",
        github: "https://github.com/purecss-co/purecss-bob-minion",
        website: "",
        design: "https://www.uplabs.com/posts/bob-minion",
        border: "",
      },
      {
        title: "Responsive Sketch Logo",
        image: "/img/sketch.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/OEvEBz",
        github: "https://github.com/purecss-co/purecss-sketch-logo",
        website: "https://www.sketchapp.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive Work Desk",
        image: "/img/workdesk.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/GGQaGM",
        github: "https://github.com/purecss-co/purecss-work-desk",
        website: "",
        design: "https://www.uplabs.com/posts/work_desk",
        border: "",
      },
      {
        title: "Responsive Discord Logo",
        image: "/img/discord.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/VdyqOa",
        github: "https://github.com/purecss-co/purecss-discord-logo",
        website: "https://discordapp.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive Angular Logo",
        image: "/img/angular.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/zappyQ",
        github: "https://github.com/purecss-co/purecss-angular-logo",
        website: "https://angular.io",
        design: "",
        border: "",
      },
      {
        title: "Responsive Reddit Loader",
        image: "/img/reddit-loader.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/OEOZVW",
        github: "https://github.com/purecss-co/purecss-reddit-loader",
        website: "https://www.reddit.com",
        design: "",
        border: "border-top",
      },
      {
        title: "Responsive Reddit Logo",
        image: "/img/reddit.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/bKYvpd",
        github: "https://github.com/purecss-co/purecss-reddit-logo",
        website: "https://www.reddit.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive Unicorn",
        image: "/img/unicorn.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/YvEpWE",
        github: "https://github.com/purecss-co/purecss-unicorn",
        website: "",
        design: "https://dribbble.com/shots/1466843-Unicorn",
        border: "",
      },
      {
        title: "Responsive Wahdah Logo",
        image: "/img/wahdah.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/bKrbRd",
        github: "https://github.com/purecss-co/purecss-wahdah-logo",
        website: "https://www.wahdah.my",
        design: "",
        border: "",
      },
      {
        title: "Responsive DigitalOcean Logo",
        image: "/img/digitalocean.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/YvVKaX",
        github: "https://github.com/purecss-co/purecss-digitalocean-logo",
        website: "https://www.digitalocean.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive WordPress Logo",
        image: "/img/wordpress.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/MXJqWb",
        github: "https://github.com/purecss-co/purecss-wordpress-logo",
        website: "https://wordpress.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive Iron Man 2 Arc Reactor",
        image: "/img/arc-reactor-2.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/XYpjjV",
        github: "https://github.com/purecss-co/purecss-ironman2-arcreactor",
        website: "",
        design: "",
        border: "",
      },
      {
        title: "Responsive Git Logo",
        image: "/img/git.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/ERyQGm",
        github: "https://github.com/purecss-co/purecss-git-logo",
        website: "https://git-scm.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive GitLab Logo",
        image: "/img/gitlab.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/VdaxqW",
        github: "https://github.com/purecss-co/purecss-gitlab-logo",
        website: "https://gitlab.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive Avengers Logo",
        image: "/img/avengers.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/RJrywp",
        github: "https://github.com/purecss-co/purecss-avengers-logo",
        website: "http://marvel.com/avengers",
        design: "",
        border: "",
      },
      {
        title: "Responsive Ubuntu Logo",
        image: "/img/ubuntu.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/PaPMYE",
        github: "https://github.com/purecss-co/purecss-ubuntu-logo",
        website: "https://www.ubuntu.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive Katsana Sticker",
        image: "/img/katsana.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/NzqJWa",
        github: "https://github.com/purecss-co/purecss-katsana-sticker",
        website: "https://www.katsana.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive Laman7 Logo",
        image: "/img/laman7.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/wXBVzb",
        github: "https://github.com/purecss-co/purecss-laman7-logo",
        website: "https://laman7.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive Shazam Listening Song",
        image: "/img/shazam.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/zaxGeg",
        github: "https://github.com/purecss-co/purecss-shazam-logo",
        website: "https://www.shazam.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive OMG Hackers Logo",
        image: "/img/omgh.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/PaYjbX",
        github: "https://github.com/purecss-co/purecss-omgh-logo",
        website: "https://omghackers.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive Amanz Logo",
        image: "/img/amanz.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/yjWKWE",
        github: "https://github.com/purecss-co/purecss-amanz-logo",
        website: "https://amanz.my",
        design: "",
        border: "",
      },
      {
        title: "Responsive JomParking Logo",
        image: "/img/jomparking.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/rKNBdE",
        github: "https://github.com/purecss-co/purecss-jomparking-logo",
        website: "https://www.jomparking.com",
        design: "",
        border: "",
      },
      {
        title: "SumberManusia Old Logo",
        image: "/img/sm.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/KRLyrZ",
        github: "https://github.com/purecss-co/purecss-sumbermanusia-logo",
        website: "https://sumbermanusia.my",
        design: "",
        border: "border-top",
      },
      {
        title: "Responsive Iron Man Arc Reactor",
        image: "/img/arc-reactor.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/odVpmE",
        github: "https://github.com/purecss-co/purecss-ironman-arcreactor",
        website: "",
        design: "",
        border: "",
      },
      {
        title: "Responsive eSentral Logo",
        image: "/img/esentral.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/odVGKr",
        github: "https://github.com/purecss-co/purecss-esentral",
        website: "https://www.e-sentral.com",
        design: "",
        border: "",
      },
      {
        title: "Responsive ReactJS Logo",
        image: "/img/reactjs.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/vjbOdE",
        github: "https://github.com/purecss-co/purecss-reactjs-logo",
        website: "https://reactjs.org",
        design: "",
        border: "",
      },
      {
        title: "Firebase Logo",
        image: "/img/firebase.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/NMoPLq",
        github: "https://github.com/purecss-co/purecss-firebase-logo",
        website: "https://firebase.google.com",
        design: "",
        border: "",
      },
      {
        title: "Deadpool Logo",
        image: "/img/deadpool.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/aGPKPg",
        github: "https://github.com/purecss-co/purecss-deadpool-logo",
        website: "",
        design: "",
        border: "",
      },
      {
        title: "The Flash Logo",
        image: "/img/theflash.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/JveQYX",
        github: "https://github.com/purecss-co/purecss-theflash-logo",
        website: "",
        design: "",
        border: "",
      },
      {
        title: "Responsive TensorFlow Logo",
        image: "/img/tensorflow.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/qVBrrv",
        github: "https://github.com/purecss-co/purecss-tensorflow-logo",
        website: "https://www.tensorflow.org",
        design: "",
        border: "border-top",
      },
      {
        title: "Responsive Runcloud Logo",
        image: "/img/runcloud.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/aVoaYr",
        github: "https://github.com/purecss-co/purecss-runcloud-logo",
        website: "https://runcloud.io",
        design: "",
        border: "",
      },
      {
        title: "iPhone 8 White Edition and Wireless Charging",
        image: "/img/iphone8.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/BwgBLe",
        github: "https://github.com/purecss-co/purecss-iphone-8",
        website: "",
        design: "",
        border: "",
      },
      {
        title: "Pixel 2 XL White Edition",
        image: "/img/pixel.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/rGRXKy",
        github: "https://github.com/purecss-co/purecss-pixel2xl",
        website: "",
        design: "",
        border: "border-top",
      },
      {
        title: "Galaxy S8 Coral Blue Edition",
        image: "/img/galaxys8.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/MELpGo",
        github: "https://github.com/purecss-co/purecss-galaxy-s8",
        website: "",
        design: "",
        border: "",
      },
      {
        title: "iPhone X White Edition",
        image: "/img/iphoneX.png",
        codepen: "https://codepen.io/AsyrafHussin/pen/mBaBXm",
        github: "https://github.com/purecss-co/purecss-iphone-x",
        website: "",
        design: "",
        border: "",
      },
    ],
  },
});

// scrollreveal
import ScrollReveal from "scrollreveal";
ScrollReveal().reveal(".card-custom", { delay: 375, duration: 1500 });

// toggle nightmode
document.getElementById("nightmode").addEventListener("click", function() {
  document.body.classList.toggle("nightmode");
  var moon = document.getElementById("moon-icon");
  moon.classList.toggle("far");
  moon.classList.toggle("fas");
  moon.classList.toggle("moon-white");
});
